# Further reading:
#   Cloud Run runtime service account   - https://cloud.google.com/run/docs/securing/service-identity
#   Cloud Run IAM permissions           - https://cloud.google.com/run/docs/deploying-source-code#permissions_required_to_deploy
#   Cloud Run builds from source        - https://cloud.google.com/run/docs/deploying-source-code
#   Principle of least privilege        - https://cloud.google.com/blog/products/identity-security/dont-get-pwned-practicing-the-principle-of-least-privilege

name: Deploy to GCP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          project_id: ece-461-part-2-web-service
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Stop previous versions 
        run: |
          PREVIOUS_VERSION=$(gcloud app versions list --service=frontend-service --sort-by='~version' --limit=2 --format='value(version.id)' | tail -1)
          gcloud app versions stop $PREVIOUS_VERSION --service=frontend-service
          PREVIOUS_VERSION=$(gcloud app versions list --service=backend-service --sort-by='~version' --limit=2 --format='value(version.id)' | tail -1)
          gcloud app versions stop $PREVIOUS_VERSION --service=backend-service
      - name: Deploy backend
        run: |
          cd website
          gcloud app deploy --account=github-continuous-deployment@ece-461-part-2-web-service.iam.gserviceaccount.com --project=ece-461-part-2-web-service
      - name: Deploy frontend
        run: |
          cd website/react
          gcloud app deploy --account=github-continuous-deployment@ece-461-part-2-web-service.iam.gserviceaccount.com --project=ece-461-part-2-web-service
      
          
