name: Validate Rust Metric Calculations

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Rust Metrics
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd repo_analyzer
        cargo build --verbose
    - name: Run tests
      run: |
        cd repo_analyzer
        cargo test --verbose
